export const AUDIT_EVENTS = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS', LOGIN_FAILED: 'LOGIN_FAILED', LOGOUT: 'LOGOUT', TOKEN_REFRESH: 'TOKEN_REFRESH',
  TOKEN_VERIFY_FAILED: 'TOKEN_VERIFY_FAILED', PASSWORD_CHANGED: 'PASSWORD_CHANGED', ROLE_CHANGED: 'ROLE_CHANGED',
  DB_CONNECTION_FAILED: 'DB_CONNECTION_FAILED', DB_FAILOVER_STARTED: 'DB_FAILOVER_STARTED', DB_FAILOVER_SUCCESS: 'DB_FAILOVER_SUCCESS',
  DB_FAILOVER_FAILED: 'DB_FAILOVER_FAILED', DB_BACKUP_STARTED: 'DB_BACKUP_STARTED', DB_BACKUP_SUCCESS: 'DB_BACKUP_SUCCESS', DB_BACKUP_FAILED: 'DB_BACKUP_FAILED',
  ADMIN_ACTION: 'ADMIN_ACTION'
} as const;
export type AuditEventType = keyof typeof AUDIT_EVENTS;
