{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: { name: sso-api }
spec: { rules: [{ host: {{ .Values.ingress.host | quote }}, http: { paths: [{ path: /, pathType: Prefix, backend: { service: { name: sso-api, port: { number: {{ .Values.service.port }} } } } }] } }] }
{{- end }}
