name: Helm Deploy Production
on: { workflow_dispatch: {} }
jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: helm lint infrastructure/helm/sso-api
